namespace ProjectEuler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 will be:<br/>
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...<br/>
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public static class Problem2
    {
        /// <summary>
        /// Iterate through the Fibonacci numbers and see if the next value is even. If it is, add it to the sum.
        /// </summary>
        /// <remarks>
        /// There is most likely an arithmetic formula which could be integrated into this solution, but I don't know of it.
        /// </remarks>
        private static int FibonacciEvenSum(int max)
        {
            int first = 1;
            int second = 2;

            int sum = 0;

            while (second < max)
            {
                int third = first + second;

                if (third % 2 == 0)
                    sum += third;

                first = second;
                second = third;
            }

            // Add 2 since it's even and outside of the for loop where sum gets incremented
            return 2 + sum;
        }

        public static void Run()
        {
            Console.WriteLine($"Problem2: {FibonacciEvenSum(4000000)}");
        }
    }
}
